#!/bin/bash

mac=$(virsh dumpxml $1 | grep "mac address" | awk -F"'" '{print $2}')

ip=$(arp -n | grep "$mac" | awk '{print $1}')

echo "$1 = $ip"

echo "$date: Your IP address for $1 is: $ip. Do note that DHCP will recycle this IP, so it is prone to change" >> VMs_IPaddr.txt 



# ssh $ip # To gain "remote" access to your VM utilziing that IP address.  

